import {TelemetryCharts} from './charts.js';
import {SessionInsights} from './insights.js';
const $=id=>document.getElementById(id);
const state={sessions:[],session:null,traces:[],axis:'distance',generation:0,importing:false};
const charts=new TelemetryCharts($('charts'),$('cursor-position'));
const insights=new SessionInsights(api);
let noticeTimer;
function notice(message,error=false,persist=false){clearTimeout(noticeTimer);$('notice').textContent=message;$('notice').classList.toggle('error',error);$('notice').hidden=false;if(!persist)noticeTimer=setTimeout(()=>$('notice').hidden=true,error?10000:4000);}
async function api(path,options={}){const response=await fetch(`/api/v1${path}`,options);if(!response.ok){let error;try{error=await response.json();}catch{error={detail:`请求失败（${response.status}）`};}throw Error(typeof error.detail==='string'?error.detail:'请求未成功');}return response.json();}
function lapTime(seconds){if(seconds==null)return '—';const ms=Math.round(seconds*1000);return `${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`;}
function dateLabel(value){if(!value)return '录制日期未提供';const normalized=String(value).replace(/T(\d{2})_(\d{2})_(\d{2})Z$/, 'T$1:$2:$3Z');const date=new Date(normalized);return Number.isNaN(date.getTime())?String(value):date.toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});}
function track(meta){return meta.TrackLayout||meta.TrackName||'未知赛道';}
function renderSessions(){const list=$('sessions');list.replaceChildren();$('session-count').textContent=state.sessions.length;if(!state.sessions.length){const p=document.createElement('p');p.className='session-empty';p.textContent='还没有练习记录。\n从一份遥测文件开始。';list.append(p);}for(const session of state.sessions){const button=document.createElement('button');button.className='session-item';button.classList.toggle('active',session.id===state.session?.id);button.setAttribute('aria-current',String(session.id===state.session?.id));const name=document.createElement('strong'),meta=document.createElement('small');name.textContent=track(session.metadata);meta.textContent=`${session.complete_lap_count} 圈 · ${dateLabel(session.metadata.RecordingTime||session.created_at)}`;button.append(name,meta);button.title=session.filename;button.addEventListener('click',()=>selectSession(session.id));list.append(button);}}
async function refreshSessions(){state.sessions=(await api('/sessions')).items;renderSessions();}
function renderSession(session){$('empty').hidden=true;$('workspace').hidden=false;$('track-name').textContent=track(session.metadata);$('car-name').textContent=[session.metadata.CarName,session.metadata.CarClass].filter(Boolean).join(' · ')||'车辆信息未提供';$('session-type').textContent=session.metadata.SessionType||'练习记录';$('best-lap').textContent=lapTime(session.best_lap_s);$('lap-count').textContent=String(session.complete_lap_count).padStart(2,'0');const fragments=session.segments.filter(s=>s.kind!=='complete').length;$('fragment-count').textContent=`另有 ${fragments} 个不完整片段`;$('duration').textContent=`${Math.floor(session.duration_s/60)}:${String(Math.floor(session.duration_s%60)).padStart(2,'0')}`;$('recorded-date').textContent=dateLabel(session.metadata.RecordingTime);$('source-file').textContent=`原始文件：${session.filename}`;$('diagnostic-count').textContent=`${session.diagnostics.length} 条读取提示`;$('diagnostics').replaceChildren();for(const d of session.diagnostics){const li=document.createElement('li');li.textContent=d.message;$('diagnostics').append(li);}for(const id of ['lap-select','reference-select']){const select=$(id);select.replaceChildren();if(id==='reference-select')select.add(new Option('不叠加参考圈',''));for(const lap of session.laps)select.add(new Option(`第 ${lap.ordinal} 圈 · ${lap.display_time||lapTime(lap.lap_time_s)}`,lap.id));select.disabled=!session.laps.length;}if(!session.laps.length){$('selection-note').textContent='未找到可展示的完整圈';notice('文件已保存，但没有可展示的完整圈。请查看读取状态。',false);}renderSessions();}
async function selectSession(id){const generation=++state.generation;insights.setSession(null);charts.setData([],state.axis);$('charts').classList.add('loading');try{const session=await api(`/sessions/${encodeURIComponent(id)}`);if(generation!==state.generation)return;state.session=session;renderSession(session);insights.setSession(session);await loadTraces();}catch(error){if(generation===state.generation){$('workspace').hidden=true;$('empty').hidden=false;notice(error.message,true);}}finally{if(generation===state.generation)$('charts').classList.remove('loading');}}
async function loadTraces(){const generation=++state.generation;const session=state.session;if(!session)return;$('charts').classList.add('loading');state.traces=[];charts.setData([],state.axis);const ids=[$('lap-select').value,$('reference-select').value].filter(Boolean);$('selection-note').textContent=ids.length===2?'双圈叠加 · 同一练习记录':'单圈查看';try{const traces=await Promise.all(ids.map(id=>api(`/sessions/${session.id}/laps/${id}/trace`)));if(generation!==state.generation)return;state.traces=traces;setAxis(state.axis);}catch(error){if(generation===state.generation)notice(error.message,true);}finally{if(generation===state.generation)$('charts').classList.remove('loading');}}
function setAxis(axis){const distanceAvailable=state.traces.length>0&&state.traces.every(t=>t.distance_available);$('axis-distance').disabled=!distanceAvailable;state.axis=axis==='distance'&&!distanceAvailable?'time':axis;$('axis-distance').setAttribute('aria-pressed',String(state.axis==='distance'));$('axis-time').setAttribute('aria-pressed',String(state.axis==='time'));$('axis-note').textContent=state.axis==='distance'?'横轴：赛道距离（m） · 两圈按各自距离叠加':`横轴：圈内时间（s）${distanceAvailable?'':' · 暂无可靠的单调距离数据'}`;charts.setData(state.traces,state.axis);}
async function importFile(file){if(!file||state.importing)return;if(!file.name.toLowerCase().endsWith('.duckdb')){notice('请选择 LMU 原生 .duckdb 文件。',true);return;}if(file.size>128*1024*1024){notice('文件超过 128 MB 上限。',true);return;}state.importing=true;document.body.classList.add('busy');$('file-input').disabled=true;notice('正在导入并解析遥测，请稍候…',false,true);try{const result=await api('/sessions',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':encodeURIComponent(file.name),'X-LMU-Client':'web'},body:file});await refreshSessions();await selectSession(result.session.id);notice(result.duplicate?'这份文件已导入，已打开现有记录。':`导入完成 · ${result.session.complete_lap_count} 个完整圈已保存到本机。`);}catch(error){notice(error.message,true);}finally{state.importing=false;document.body.classList.remove('busy');$('file-input').disabled=false;$('file-input').value='';}}
$('file-input').addEventListener('change',e=>importFile(e.target.files[0]));$('empty-import').addEventListener('click',()=>$('file-input').click());
for(const event of ['dragenter','dragover'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.add('dragover');});
for(const event of ['dragleave','drop'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.remove('dragover');if(event==='drop')importFile(e.dataTransfer.files[0]);});
window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>e.preventDefault());
$('lap-select').addEventListener('change',loadTraces);$('reference-select').addEventListener('change',loadTraces);$('axis-distance').addEventListener('click',()=>setAxis('distance'));$('axis-time').addEventListener('click',()=>setAxis('time'));$('reset-zoom').addEventListener('click',()=>charts.reset());
async function start(){try{const me=await api('/me');$('driver-name').textContent=me.display_name;await refreshSessions();if(state.sessions.length)await selectSession(state.sessions[0].id);}catch(error){notice(`无法连接本地服务：${error.message}`,true);}}start();
