const $=id=>document.getElementById(id);
const LABELS={candidate:'可视化候选',mapping_review:'分量对应待核实',timing_review:'时间轴待核实',constant:'本样本为常量',missing:'暂无可用数值'};
const KIND={'continuous':'连续通道','event':'事件'};
const CHINESE={'Engine RPM':'发动机转速','Fuel Level':'燃油量','G Force Lat':'横向 G 值','G Force Long':'纵向 G 值','G Force Vert':'垂向 G 值','FFB Output':'力反馈输出','Steering Shaft Torque':'转向轴扭矩','TyresPressure':'轮胎压力','Tyres Wear':'轮胎磨损','TyresCarcassTemp':'胎体温度','TyresRimTemp':'轮辋温度','TyresRubberTemp':'轮胎橡胶温度','TyresTempCentre':'轮胎中部温度','TyresTempLeft':'轮胎左侧温度','TyresTempRight':'轮胎右侧温度','Brakes Temp':'刹车温度','Brakes Air Temp':'刹车空气温度','Brake Thickness':'刹车厚度','Brakes Force':'刹车力','Susp Pos':'悬挂位置','RideHeights':'车身高度','FrontRideHeight':'前部车身高度','RearRideHeight':'后部车身高度','Front3rdDeflection':'前第三弹簧位移','Rear3rdDeflection':'后第三弹簧位移','Engine Oil Temp':'发动机油温','Engine Water Temp':'发动机水温','Turbo Boost Pressure':'涡轮增压压力','GPS Latitude':'纬度字段','GPS Longitude':'经度字段','GPS Speed':'GPS 速度','Track Temperature':'赛道温度','Ambient Temperature':'环境温度','Wind Heading':'风向','Wind Speed':'风速','Wheel Speed':'车轮速度','Virtual Energy':'虚拟能量','Regen Rate':'能量回收功率','SoC':'电池荷电状态','ABS':'ABS 状态','TC':'牵引力控制状态','Clutch Pos':'离合输入','Brake Bias Rear':'后刹车偏置','Throttle Pos Unfiltered':'未滤波油门','Brake Pos Unfiltered':'未滤波刹车','Steering Pos Unfiltered':'未滤波转向'};
function el(tag,text,className){const node=document.createElement(tag);if(text!=null)node.textContent=text;if(className)node.className=className;return node;}
function lapTime(value){if(value==null)return '—';const ms=Math.round(value*1000);return `${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`;}
function seconds(value){return value==null?'—':`${value.toFixed(3)}`;}
function number(value){return value==null?'—':new Intl.NumberFormat('zh-CN',{maximumFractionDigits:3}).format(value);}

export class SessionInsights {
  constructor(api){this.api=api;this.session=null;this.generation=0;this.active=['timing','inventory','conditions'].includes(location.hash.slice(1))?location.hash.slice(1):'telemetry';this.data={};
    document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>this.show(button.dataset.view)));
    $('inventory-search').addEventListener('input',()=>this.renderInventory());$('inventory-filter').addEventListener('change',()=>this.renderInventory());
    this.show(this.active);
  }
  setSession(session){this.session=session;this.generation++;this.data={};for(const view of ['timing','inventory']){$(`${view}-content`).hidden=true;$(`${view}-status`).textContent='';}this.load();}
  show(view){this.active=view;for(const name of ['telemetry','timing','inventory','conditions'])$(`view-${name}`).hidden=name!==view;document.querySelectorAll('[data-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.view===view)));history.replaceState(null,'',view==='telemetry'?location.pathname:`#${view}`);this.load();}
  async load(){const view=this.active;if(!this.session||['telemetry','conditions'].includes(view)||this.data[view])return;const generation=this.generation;const sessionId=this.session.id;const status=$(`${view}-status`);status.textContent=view==='timing'?'正在核对圈次和分段计时…':'正在检查原始通道的采样与数值…';try{const data=await this.api(`/sessions/${sessionId}/${view}`);if(generation!==this.generation)return;this.data[view]=data;status.textContent='';$(`${view}-content`).hidden=false;if(view==='timing')this.renderTiming();else this.renderInventory();}catch(error){if(generation===this.generation)status.textContent=`读取失败：${error.message}。点击本页标签重试。`;}}
  renderTiming(){const data=this.data.timing,s=data.statistics;$('timing-count').textContent=`${s.count} 圈参与统计`;$('timing-best').textContent=lapTime(s.best_s);$('timing-average').textContent=lapTime(s.average_s);$('timing-average-note').textContent=`排除 ${s.excluded_count} 个残圈或其他不适用片段`;$('timing-theoretical').textContent=lapTime(s.theoretical_s);$('timing-stddev').textContent=s.stddev_s==null?'—':`${s.stddev_s.toFixed(3)} s`;$('timing-scope').textContent=data.scope;$('timing-method').textContent=data.sector_method;$('timing-extra').textContent=`中位圈速 ${lapTime(s.median_s)} · 最慢圈速 ${lapTime(s.slowest_s)}${s.gap_to_theoretical_s==null?'':` · 最快记录圈与理论最快相差 ${s.gap_to_theoretical_s.toFixed(3)} s`}。理论最快是分段组合，不是实际跑出的圈。`;
    const sectors=$('sector-summary');sectors.replaceChildren();s.best_sectors_s.forEach((value,i)=>{const card=el('div',null,'sector-card');card.append(el('span',`BEST S${i+1}`),el('strong',value==null?'—':`${seconds(value)} s`),el('small',s.best_sector_laps[i].length?`来自第 ${s.best_sector_laps[i].join('、')} 圈`:'没有可核对的分段'));sectors.append(card);});
    const body=$('timing-rows');body.replaceChildren();for(const row of data.rows){const tr=el('tr',null,row.eligible?'':'excluded-row');const title=el('td');title.append(el('strong',row.ordinal?`第 ${row.ordinal} 圈`:row.label),el('small',`源圈计数 ${row.source_lap}`));tr.append(title);const time=el('td',lapTime(row.lap_time_s),row.is_best?'best-lap-cell':'');if(row.is_best)time.append(el('small','本次最快'));tr.append(time);row.sectors_s.forEach((value,i)=>{const td=el('td',seconds(value),row.best_sectors[i]?'best-sector-cell':'');td.title=row.sector_sources[i]||'没有可核对的计时';tr.append(td);});tr.append(el('td',row.delta_best_s==null?'—':`+${seconds(row.delta_best_s)}`, 'delta-cell'));const status=el('td');status.append(el('span',row.eligible?'纳入统计':row.exclusion_reason,'table-badge'),el('small',row.eligible?'有效性未核实':`观测时长 ${lapTime(row.observed_duration_s)}`));if(row.notes.length){const note=el('small',row.notes.join('；'),'row-note');status.append(note);}tr.append(status);body.append(tr);}
    if(!data.rows.length){const tr=el('tr'),td=el('td','没有可识别的圈次。');td.colSpan=7;tr.append(td);body.append(tr);}
    const footer=$('timing-totals');footer.replaceChildren();const tr=el('tr');tr.append(el('th','理论组合'),el('td',lapTime(s.theoretical_s)));s.best_sectors_s.forEach(value=>tr.append(el('td',seconds(value))));tr.append(el('td','—'),el('td','各段独立取最短'));footer.append(tr);
  }
  renderInventory(){const data=this.data.inventory;if(!data)return;$('inventory-count').textContent=`${data.continuous_count} 通道 / ${data.event_count} 事件`;$('inventory-note').textContent=data.note;const search=$('inventory-search').value.trim().toLowerCase(),filter=$('inventory-filter').value;const rows=data.items.filter(item=>{const text=[item.source_name,item.category,CHINESE[item.source_name]||'',item.note].join(' ').toLowerCase();return text.includes(search)&&(filter==='all'||filter==='new'&&!item.displayed&&!item.timing_used||filter==='candidate'&&item.status==='candidate'||filter==='review'&&item.status.endsWith('_review')||filter==='constant'&&item.status==='constant');});$('inventory-results').textContent=`显示 ${rows.length} / ${data.items.length}`;const body=$('inventory-rows');body.replaceChildren();for(const item of rows){const tr=el('tr'),name=el('td');name.append(el('strong',CHINESE[item.source_name]||item.source_name));if(CHINESE[item.source_name])name.append(el('small',item.source_name));name.append(el('small',item.category));tr.append(name);const sampling=el('td');sampling.append(el('span',item.kind==='continuous'?`${number(item.frequency_hz)} Hz`:'事件时间戳'),el('small',`${number(item.rows)} 条 · ${KIND[item.kind]}`));tr.append(sampling);const values=el('td');for(const comp of item.components){const text=`${item.components.length>1?`${comp.name}: `:''}${number(comp.min)} ～ ${number(comp.max)} ${item.unit||'(源单位未标注)'}`;values.append(el('div',text,'range-value'));if(comp.missing_count)values.append(el('small',`${comp.missing_count} 条缺失 / 非数值`));}if(!item.components.length)values.textContent='—';tr.append(values);const verdict=el('td');verdict.append(el('span',item.displayed?'已用于驾驶曲线':item.timing_used?'已用于圈速页':LABELS[item.status],`table-badge ${item.status}`),el('small',item.note));tr.append(verdict);body.append(tr);}if(!rows.length){const tr=el('tr'),td=el('td','没有匹配的通道，请更换搜索条件。');td.colSpan=4;tr.append(td);body.append(tr);}}
}
